name: meshtastic-web build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository
      - name: Checkout
        uses: actions/checkout@v2

      # Build project
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install --ignore-optional
      - run: yarn lint
      - run: yarn build
      - run: yarn package
      - run: tree build/output
      
      # Create a zip file from the output folder
      - name: Create output zip file
        uses: papeloto/action-zip@v1
        with:
          files: build/output/
          dest: output.zip
    
      # Upload Artifact
      - name: Upload a Build Artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            output.zip
